include(FindPackageHandleStandardArgs)

find_path(CODEMETER_INCLUDE_DIR CodeMeter.h
    PATHS
    ${CODEMETER_ROOT}/include
    )

find_library(CODEMETER_CODEMETER_LIBRARY WibuCm64
    PATHS
    ${CODEMETER_ROOT}/lib/
    )

# Read codemeter version
if(CODEMETER_INCLUDE_DIR AND EXISTS "${CODEMETER_INCLUDE_DIR}/CodeMeter.h")
  file(STRINGS "${CODEMETER_INCLUDE_DIR}/CodeMeter.h" CODE_METER_VERSION_STRING REGEX "#define CODEMETER_VERSION")
  separate_arguments(CODE_METER_VERSION_STRING)

  list (GET CODE_METER_VERSION_STRING 2 CODE_METER_VERSION_STRIP)

  #/* Define Version for this header file as MAJOR * 100 + MINOR */
  string(SUBSTRING ${CODE_METER_VERSION_STRIP} 0 1  CODEMETER_VERSION_MAJOR_FOUND)
  string(SUBSTRING ${CODE_METER_VERSION_STRIP} 1 2 CODEMETER_VERSION_MINOR_FOUND)
  set (CODE_METER_VERSION_FOUND  ${CODEMETER_VERSION_MAJOR_FOUND}.${CODEMETER_VERSION_MINOR_FOUND})
endif()

find_package_handle_standard_args(
  codemeter DEFAULT_MSG CODEMETER_INCLUDE_DIR CODEMETER_CODEMETER_LIBRARY VERSION_VAR CODE_METER_VERSION_FOUND)

set(CODEMETER_INCLUDE_DIRS ${CODEMETER_INCLUDE_DIR})
set(CODEMETER_LIBRARIES ${CODEMETER_CODEMETER_LIBRARY})
mark_as_advanced(CUDNN_INCLUDE_DIRS CODEMETER_LIBRARIES)
 
if(CODEMETER_FOUND)
  if(CODEMETER_LIBRARIES)
    add_library(codemeter::wibucm SHARED IMPORTED)
    set_target_properties(codemeter::wibucm PROPERTIES
                            IMPORTED_IMPLIB "${CODEMETER_CODEMETER_LIBRARY}"
                            INTERFACE_INCLUDE_DIRECTORIES "${CODEMETER_INCLUDE_DIRS}"
                            TARGET_DEPENDENCIES_COMMON   "${CODEMETER_ROOT}/bin/WibuCm64.dll"
                            TARGET_DEPENDENCIES_DEBUG ""
                            TARGET_DEPENDENCIES_RELEASE ""
    )
  endif()
endif()
